.github/actions/auto-patch-release-v1/action.yml
.github/actions/cancel-if-release-pr-exists/action.yml

Tested on devtools-pip
Action when there was a release PR: https://github.com/dequelabs/axe-devtools-pip/actions/runs/5413935143
Action when no open release PRs: https://github.com/dequelabs/axe-devtools-pip/actions/runs/5413958185/jobs/9840298492

ci: cancel auto-release if a PR already exists

---

.github/actions/auto-patch-release-v1/action.yml

``` 
The expr utility exits with one of the following values:
0       the expression is neither an empty string nor 0.
1       the expression is an empty string or 0.
2       the expression is invalid.
```
Why
The date code was tested in a local bash script then copy-pasted into the action. Said script didn't have exit-on-error, so this behavior was not found.
Also fixes an issue found when running on axe-core-npm's release script

ci(auto-patch): fix date check

---

.github/actions/auto-major-minor-release-v1/action.yml
.github/actions/auto-patch-release-v1/action.yml

Part of the work to make our actions more testable. Adds an argument to them that allows you to skip checks that cancel the job.
Tested on a personal repo: https://github.com/AdnoC/action-test/blob/master/.github/workflows/push-and-dispatch.yml

ci: enable skipping cancel checks

---

.eslintignore
.eslintrc.js
.gitignore
.husky/pre-commit.sh
.mocharc.json
.prettierignore
.prettierrc.json
LICENSE
package-lock.json
package.json
tsconfig.json

Adding everything that was missing so we can start adding code files and not just `action.yml` files.

chore: add typescript, prettier, eslint, and other standards

---

.github/chore: add `CODEOWNERS` file

I was wondering why I wasn't getting any GH notifications when PR's were getting created here. Added code owners so we get notified

chore: add `CODEOWNERS` file

---

.github/actions/is-release-in-progress-v1/dist/index.js
.github/actions/is-release-in-progress-v1/package.json
.github/actions/is-release-in-progress-v1/src/index.ts

This PR fixes an issue with using the build action, we not exporting everything required for `core` when importing into `index.ts`
see: https://github.com/dequelabs/zidious-testing/actions/runs/6411034143/job/17405607381#step:2:94
No QA Required

fix(.github/actions/is-release-in-progress-v1): include required functions and rebuild dist

---

.github/actions/create-project-issue-v1/action.yml

Causing the action to 404 when attempting to create issue cross repo 
https://github.com/dequelabs/zidious-testing/actions/runs/6423572944/job/17442362207#step:3:93
No QA Required

fix: use correct token in create-project-issue composite actions

---

.github/actions/create-project-issue-v1/README.md
.github/actions/create-project-issue-v1/action.yml

Attempting to access an output from the composite errors as we do not forward the output. 
```
uses: dequelabs/axe-api-team-public/.github/actions/create-project-issue-v1@main
id: create_issue
uses: another-action
value: ${{ steps.create_issue_outputs_html_url }}
```

fix(.github/actions/create-project-issue-v1): emit outputs from composite action

---

.github/actions/create-release-candidate-v1/README.md
.github/actions/create-release-candidate-v1/action.yml

Closes: https://github.com/dequelabs/axe-api-team/issues/405

chore(.github/actions): remove slack notification from RC workflow

---

.github/actions/update-axe-core-v1/README.md
.github/actions/update-axe-core-v1/action.yml
.github/actions/update-axe-core-v1/src/run.test.ts
.github/actions/update-axe-core-v1/src/run.ts

Didn't realize that the version number was needed in the pr title when creating a pr release.

fix(update-axe-core): add version output

---

.github/actions/create-update-axe-core-pull-request-v1/README.md
.github/actions/create-update-axe-core-pull-request-v1/action.yml
.github/actions/update-axe-core-v1/dist/index.js
.github/actions/update-axe-core-v1/src/run.test.ts
.github/actions/update-axe-core-v1/src/run.ts

Creates a single action to update axe-core and open a pull request. We investigated using dependabot to do this for us as it maintains the pinning strategy, but dependabot does not allow multiple entries for different ecosystems. So we can't define both a monthly cadence for everything excluding axe-core and a daily cadence for axe-core.
Requires: https://github.com/dequelabs/axe-api-team-public/pull/65
Closes: https://github.com/dequelabs/update-axe-core/issues/9
Closes: https://github.com/dequelabs/axe-api-team-public/issues/30
Successful action run: https://github.com/dequelabs/straker-test-repo/actions/runs/6549902423/job/17787837546
Pr to update axe-core: https://github.com/dequelabs/straker-test-repo/pull/20
Action cancel after up-to-date: …

feat: add create-update-axe-core-pull-request-v1

---

.github/actions/create-update-axe-core-pull-request-v1/README.md
.github/actions/create-update-axe-core-pull-request-v1/action.yml
.github/actions/update-axe-core-v1/README.md

Noticed a typo in the name of `create-update-axe-pull-core-request-v1`, cleaned up readme while I was updating anyway to make it more obvious to a reader exactly what "update" means
No QA required.

chore: fix name and improve READMEs for *update-axe-core* actions

---

.github/actions/semantic-pr-footer-v1/README.md
.github/actions/semantic-pr-footer-v1/action.yml
.github/actions/semantic-pr-footer-v1/dist/index.js
.github/actions/semantic-pr-footer-v1/dist/run.d.ts
.github/actions/semantic-pr-footer-v1/dist/types.d.ts
.github/actions/semantic-pr-footer-v1/src/index.ts
.github/actions/semantic-pr-footer-v1/src/run.test.ts
.github/actions/semantic-pr-footer-v1/src/run.ts
.github/actions/semantic-pr-footer-v1/src/types.ts

This PR adds a list of known github actors to ignore when validating a PR footer. Users of this action can add additional actors if they so choose. But we should try to keep the list centralised so we don't have to go and update every repo that uses this action. 
Closes: https://github.com/dequelabs/axe-api-team-public/issues/98

fix(.github/actions/semanetic-pr-footer-v1): add a list of known gitub actors to skip validation

---

.github/actions/get-release-issue-v1/dist/index.js
.github/actions/get-release-issue-v1/src/run.test.ts
.github/actions/get-release-issue-v1/src/run.ts

Without setting the output when there are no issues found causes the workflow to proceed to the next step even though the step has a `!= ''` check, we have to set the output. 
ref: https://github.com/dequelabs/zidious-testing/actions/runs/7453971019/job/20280393389#step:2:109
No QA Required

fix(.github/actions/get-release-issue-v1): ensure output is set to null when no release issue is found

---

.github/actions/create-update-axe-core-pull-request-v1/action.yml

Setup node caching to npm requires a lock file to exist on the root which not all repos have.  
[axe-core-nuget](https://github.com/dequelabs/axe-core-nuget)
[axe-core-gems](https://github.com/dequelabs/axe-core-gems)
Ref: https://stackoverflow.com/a/68717538
no qa required

fix(create-update-axe-core-pull-request-v1): remove caching to allow use in monorepos

---

.github/workflows/update-generated-files.yml

Missed the `--base` tag in the `pr create` command that pointed to `develop` still.
no qa required

ci(update-generated-files): fix the base branch when creating pr

---

.github/workflows/update-generated-files.yml
.husky/build-changed-files.sh
.husky/pre-commit

Turns out that Github actions don't use `bash` as the shell script when running a file with `sh`. Husky runs all hook scripts using the `sh` command which would break in Github actions. Changed to separate the file out in order to get bash commands (needed for reading the list of diff files into an array and parsing unique values out) and invoking the file specifically with `bash`.
no qa required

chore: fix husky precommit hook not running code in bash

---

.github/actions/update-axe-core-v1/dist/index.js
.github/actions/update-axe-core-v1/src/run.test.ts
.github/actions/update-axe-core-v1/src/run.ts

Using yarn in github action for some reason fails when there is a space prior to the dependency you want to update. 
no qa required

fix: add dependency type after dependency

---

.github/actions/create-release-candidate-v1/README.md
.github/actions/create-release-candidate-v1/action.yml

Add optional input `should-checkout` that will add default to `true` that will checkout the repo otherwise when passed `should-checkout: 'false'` the action caller will need to checkout the repo. 
No QA Required

chore(.github/actions): add input to optionally checkout create-release-candidate-v1

---

.github/actions/label-and-move-released-issues-v1/README.md
.github/actions/label-and-move-released-issues-v1/action.yml
.github/actions/label-and-move-released-issues-v1/dist/index.js
.github/actions/label-and-move-released-issues-v1/src/run.test.ts
.github/actions/label-and-move-released-issues-v1/src/run.ts
.github/actions/move-released-issues-and-create-sync-pr-v1/README.md
.github/actions/move-released-issues-and-create-sync-pr-v1/action.yml

Added the input `column-name` in the `label-and-move-released-issues` and `move-released-issues-and-create-sync-pr` actions.
Closes: [#505](https://github.com/dequelabs/axe-api-team/issues/505)

feat(.github/action): change the label-and-move-released-issues and move-released-issues-and-create-sync-pr actions to change a column name

---

.github/actions/update-axe-core-v1/dist/index.js
.github/actions/update-axe-core-v1/dist/installScript.d.ts
.github/actions/update-axe-core-v1/src/installScript.test.ts
.github/actions/update-axe-core-v1/src/installScript.ts
.github/actions/update-axe-core-v1/src/run.test.ts
.github/actions/update-axe-core-v1/src/run.ts

Verified locally that running `npx ts-node ~/repos/axe-api-team-public/.github/actions/update-axe-core-v1/src/index.ts` from within my `axe-core-npm` clone before this PR adds the same `undefined` refs that we saw in https://github.com/dequelabs/axe-core-npm/pull/1054 and that after this PR it doesn't.
Closes: #112

fix(update-axe-core): avoid installing "undefined" in npm-based repos

---

.github/actions/create-release-candidate-v1/action.yml

Added a docs issue URL into the release issue template
Closes: #165

ci(.github/action): add a docs issue url into the create-release-candidate action

---

.github/actions/create-release-v1/action.yml

When the `migrations-dir` input is given and there are no new migration files found we would error: 
https://github.com/dequelabs/zidious-testing/actions/runs/9162107575/job/25188409931#step:2:147
This was not intended behaviour - instead we gracefully handle finding no `.sql` files to an empty string. This results in the create-release action to complete: 
PR created: https://github.com/dequelabs/zidious-testing/pull/135
When there is a new migration file found: 
Workflow: https://github.com/dequelabs/zidious-testing/actions/runs/9162710013
PR created: https://github.com/dequelabs/zidious-testing/pull/138
Closes: https://github.com/dequelabs/axe-api-team-public/issues/162

fix(create-release): ensure action does not fail when migrations dir is provided but no new files are found

---

.github/actions/abort-release-candidate-v1/action.yml

This allows the checkout action to checkout the `release` branch using the PAT token provided which has the required permission scopes for resetting.
No QA Required

fix(abort-release-candidate): pass PAT to checkout

---

.github/actions/abort-release-candidate-v1/README.md
.github/actions/abort-release-candidate-v1/action.yml

Added an optional release candidate version input to abort the exact RC. If this input is not provided the GHA will take the version from `lerna.json` (if it exists) or from the `package.json`.
Closes: [#513](https://github.com/dequelabs/axe-api-team/issues/513)

ci(.github/action): add release candidate version input in the abort-release-candidate action

---

.github/dependabot.yml

As of v6 of conventional-commits-parser it is now [ESM only](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/CHANGELOG.md#600-2024-04-26)
Ref: https://github.com/dequelabs/axe-api-team-public/pull/177
No QA Required

ci: pin conventional-commits-parser >=6 due to ESM

---

.github/actions/label-and-move-released-issues-v1/dist/index.js
.github/actions/label-and-move-released-issues-v1/dist/label-and-move-released-issues-v1/src/getReferencedClosedIssues.d.ts
.github/actions/label-and-move-released-issues-v1/src/getReferencedClosedIssues.test.ts
.github/actions/label-and-move-released-issues-v1/src/getReferencedClosedIssues.ts
.github/actions/label-and-move-released-issues-v1/src/run.test.ts
.github/actions/label-and-move-released-issues-v1/src/run.ts

Changed the label-and-move-released-issues action to work with the issue owner and the issue repo. Before the changes, we had an error if an issue in a PR was related to another repo (a different repo that a PR is related to). Right now this action will work with the issue's repo name.
Ref: [#518](https://github.com/dequelabs/axe-api-team/issues/518)

ci(.github/action): change the label-and-move-released-issues action to work with the issue owner and the issue repo

---

.github/actions/label-and-move-released-issues-v1/README.md
.github/actions/label-and-move-released-issues-v1/action.yml

Blame jenn - 🍐 _forced_ me to update to 186 (bass team board).
No QA Required

fix: update default board to point to new bass team

---

.github/actions/semantic-pr-footer-v1/README.md

See https://github.com/dequelabs/launchpad/pull/66#issuecomment-2243844743
QA notes: I like doggies

docs(semantic-pr-footer): Make allowed footers known

---

.github/actions/semantic-pr-footer-v1/README.md
.github/actions/semantic-pr-footer-v1/dist/index.js
.github/actions/semantic-pr-footer-v1/src/isValidFooter.test.ts
.github/actions/semantic-pr-footer-v1/src/isValidFooter.ts

👋  @stephenmathieson 
Closes https://github.com/dequelabs/axe-api-team-public/issues/195

feat(semantic-pr-footer): allow omission of colon in footer prefixes

---

.github/actions/create-update-axe-core-pull-request-v1/README.md
.github/actions/create-update-axe-core-pull-request-v1/action.yml

This patch adds optional input `should-setup-node` which defaults to `true` to maintain existing behavior. Some repos already setup node in a previous step in the action with a particular version there is no need to re-setup node as it could checkout with a previous version of Node and/or waste minutes.
No QA Required

feat(.github/actions): add optional `setup-node` in update-axe-core action

---

.github/actions/abort-release-candidate-v1/action.yml
.github/actions/add-to-board-v1/README.md
.github/actions/add-to-board-v1/action.yml
.github/actions/auto-major-minor-release-v1/action.yml
.github/actions/auto-patch-release-v1/action.yml
.github/actions/create-project-issue-v1/README.md
.github/actions/create-project-issue-v1/action.yml
.github/actions/create-release-candidate-v1/action.yml
.github/actions/label-and-move-released-issues-v1/README.md
.github/actions/label-and-move-released-issues-v1/action.yml
.github/actions/move-released-issues-and-create-sync-pr-v1/README.md
.github/actions/move-released-issues-and-create-sync-pr-v1/action.yml
.github/actions/release-candidate-ready-for-qa-v1/action.yml

Changed all the action and workflow files to work with the new `team-results` board and Slack channel
Closes: [#4](https://github.com/dequelabs/results-team/issues/4)

chore(.github/action): change `project-number`, `column-name`, Slack channel for the new team-results team

---

.github/actions/check-and-move-issue-based-on-labels-v1/dist/check-and-move-issue-based-on-labels-v1/src/getIssueLabels.d.ts
.github/actions/check-and-move-issue-based-on-labels-v1/dist/check-and-move-issue-based-on-labels-v1/src/types.d.ts
.github/actions/check-and-move-issue-based-on-labels-v1/dist/index.js
.github/actions/check-and-move-issue-based-on-labels-v1/src/getIssueLabels.test.ts
.github/actions/check-and-move-issue-based-on-labels-v1/src/getIssueLabels.ts
.github/actions/check-and-move-issue-based-on-labels-v1/src/run.test.ts
.github/actions/check-and-move-issue-based-on-labels-v1/src/run.ts
.github/actions/check-and-move-issue-based-on-labels-v1/src/types.ts

Move the logic of getting issue details to the separate function `getIssueLabels` to reuse it in another GHA.
No QA needed

refactor(action): refactor the GHA `check-and-move-issue-based-on-labels-v1`

---

.github/actions/create-update-axe-core-pull-request-v1/action.yml
.github/actions/update-axe-core-v1/README.md
.github/workflows/tests.yml
.github/workflows/update-generated-files.yml

Updates our actions to use node 22 (instead of 18/20). Unfortunately composite actions cannot do the same since the [actions/runner does not support it](https://github.com/actions/runner/issues/3600). We'll have to use `node24` when we update to that.
No QA required

fix: update to use node 22 in actions
